// <auto-generated />
using System;
using AklniResturant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AklniResturant.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AklniResturant.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Egyptian Dishes"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Grilled"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Seafood"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Sandwiches"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salads"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Drinks"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("AklniResturant.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Name = "Rice"
                        },
                        new
                        {
                            IngredientId = 2,
                            Name = "Lentils"
                        },
                        new
                        {
                            IngredientId = 3,
                            Name = "Pasta"
                        },
                        new
                        {
                            IngredientId = 4,
                            Name = "Tomato Sauce"
                        },
                        new
                        {
                            IngredientId = 5,
                            Name = "Fried Onions"
                        },
                        new
                        {
                            IngredientId = 6,
                            Name = "Garlic"
                        },
                        new
                        {
                            IngredientId = 7,
                            Name = "Chili Pepper"
                        },
                        new
                        {
                            IngredientId = 8,
                            Name = "Cumin"
                        },
                        new
                        {
                            IngredientId = 9,
                            Name = "Coriander"
                        },
                        new
                        {
                            IngredientId = 10,
                            Name = "Beef"
                        },
                        new
                        {
                            IngredientId = 11,
                            Name = "Chicken"
                        },
                        new
                        {
                            IngredientId = 12,
                            Name = "Kebda"
                        },
                        new
                        {
                            IngredientId = 13,
                            Name = "Sogo2"
                        },
                        new
                        {
                            IngredientId = 14,
                            Name = "Molokhia Leaves"
                        },
                        new
                        {
                            IngredientId = 15,
                            Name = "Bamia"
                        },
                        new
                        {
                            IngredientId = 16,
                            Name = "Fish Fillet"
                        },
                        new
                        {
                            IngredientId = 17,
                            Name = "Shrimp"
                        },
                        new
                        {
                            IngredientId = 18,
                            Name = "Tahina"
                        },
                        new
                        {
                            IngredientId = 19,
                            Name = "Chickpeas"
                        },
                        new
                        {
                            IngredientId = 20,
                            Name = "Ful"
                        },
                        new
                        {
                            IngredientId = 21,
                            Name = "Parsley"
                        },
                        new
                        {
                            IngredientId = 22,
                            Name = "Lemon Juice"
                        },
                        new
                        {
                            IngredientId = 23,
                            Name = "Olive Oil"
                        },
                        new
                        {
                            IngredientId = 24,
                            Name = "Flour"
                        },
                        new
                        {
                            IngredientId = 25,
                            Name = "Sugar"
                        },
                        new
                        {
                            IngredientId = 26,
                            Name = "Milk"
                        },
                        new
                        {
                            IngredientId = 27,
                            Name = "Nuts (Pistachio, Almond, Walnut)"
                        },
                        new
                        {
                            IngredientId = 28,
                            Name = "Butter or Ghee"
                        },
                        new
                        {
                            IngredientId = 29,
                            Name = "Honey or Syrup"
                        },
                        new
                        {
                            IngredientId = 30,
                            Name = "Mint Leaves"
                        },
                        new
                        {
                            IngredientId = 31,
                            Name = "Tea Leaves"
                        },
                        new
                        {
                            IngredientId = 32,
                            Name = "Coffee Beans"
                        },
                        new
                        {
                            IngredientId = 33,
                            Name = "Mango"
                        },
                        new
                        {
                            IngredientId = 34,
                            Name = "Guava"
                        },
                        new
                        {
                            IngredientId = 35,
                            Name = "Strawberry"
                        });
                });

            modelBuilder.Entity("AklniResturant.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AklniResturant.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AklniResturant.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Traditional Egyptian mix of rice, lentils, pasta, tomato sauce, and fried onions.",
                            Name = "Koshary",
                            Price = 45.0,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Rich green molokhia soup served with rice and roasted chicken.",
                            Name = "Molokhia with Chicken",
                            Price = 70.0,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Okra stew cooked with tender beef cubes and tomato sauce.",
                            Name = "Bamia with Meat",
                            Price = 80.0,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "Layers of crispy bread, rice, and meat topped with garlic tomato sauce.",
                            Name = "Fattah",
                            Price = 90.0,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "Classic Egyptian fava beans with olive oil, cumin, and lemon.",
                            Name = "Ful Medames",
                            Price = 25.0,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Juicy minced beef skewers grilled to perfection.",
                            Name = "Grilled Kofta",
                            Price = 85.0,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            Description = "Charcoal-grilled marinated chicken served with salad and tahina.",
                            Name = "Grilled Chicken",
                            Price = 95.0,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Description = "Alexandrian-style liver sautéed with garlic and chili.",
                            Name = "Liver (Kebda Eskandarani)",
                            Price = 70.0,
                            Stock = 18
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            Description = "Spicy grilled Egyptian sausages with garlic and cumin.",
                            Name = "Grilled Sogo2",
                            Price = 75.0,
                            Stock = 18
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3,
                            Description = "Crispy fried fish fillet served with rice and tahina sauce.",
                            Name = "Fried Fish Fillet",
                            Price = 110.0,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            Description = "Fresh shrimp grilled with lemon, garlic, and olive oil.",
                            Name = "Grilled Shrimp",
                            Price = 140.0,
                            Stock = 12
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            Description = "Basmati rice cooked with mixed seafood and herbs.",
                            Name = "Seafood Rice",
                            Price = 130.0,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 4,
                            Description = "Spicy liver sandwich with tahina and pickles.",
                            Name = "Kebda Sandwich",
                            Price = 35.0,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4,
                            Description = "Egyptian sausage sandwich with chili and garlic.",
                            Name = "Sogo2 Sandwich",
                            Price = 40.0,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4,
                            Description = "Tender beef or chicken shawarma wrapped in pita with garlic sauce.",
                            Name = "Shawarma Sandwich",
                            Price = 50.0,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            Description = "Deep-fried chickpea balls with tahina and salad in pita bread.",
                            Name = "Falafel Sandwich",
                            Price = 30.0,
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 5,
                            Description = "Creamy tahina dip flavored with lemon and garlic.",
                            Name = "Tahina Salad",
                            Price = 15.0,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 5,
                            Description = "Egyptian-style salad with tomatoes, cucumbers, onions, and parsley.",
                            Name = "Baladi Salad",
                            Price = 20.0,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 5,
                            Description = "Healthy chickpea salad with olive oil and lemon dressing.",
                            Name = "Chickpea Salad",
                            Price = 25.0,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 6,
                            Description = "Refreshing black tea infused with fresh mint leaves.",
                            Name = "Mint Tea",
                            Price = 20.0,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 6,
                            Description = "Strong traditional coffee served in a small cup.",
                            Name = "Turkish Coffee",
                            Price = 25.0,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 6,
                            Description = "Freshly blended mango juice made from ripe mangoes.",
                            Name = "Mango Juice",
                            Price = 30.0,
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 6,
                            Description = "Thick and sweet guava juice served cold.",
                            Name = "Guava Juice",
                            Price = 30.0,
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 6,
                            Description = "Creamy strawberry smoothie with milk and honey.",
                            Name = "Strawberry Smoothie",
                            Price = 35.0,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 7,
                            Description = "Sweet semolina cake soaked in syrup and topped with nuts.",
                            Name = "Basbousa",
                            Price = 25.0,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 7,
                            Description = "Layers of pastry filled with nuts and honey syrup.",
                            Name = "Baklava",
                            Price = 35.0,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 7,
                            Description = "Creamy rice pudding with milk and cinnamon.",
                            Name = "Rice Pudding",
                            Price = 30.0,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 7,
                            Description = "Traditional Egyptian dessert made with puff pastry, milk, and nuts.",
                            Name = "Om Ali",
                            Price = 40.0,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("AklniResturant.Models.ProductIngredient", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ProdIngredients");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 3
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 4
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 5
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 8
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 14
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 11
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 22
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 15
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 4
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 8
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 4
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 20
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 8
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 22
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 23
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 8
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 9
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 11
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 21
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 22
                        },
                        new
                        {
                            ProductId = 8,
                            IngredientId = 12
                        },
                        new
                        {
                            ProductId = 8,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 8,
                            IngredientId = 7
                        },
                        new
                        {
                            ProductId = 9,
                            IngredientId = 13
                        },
                        new
                        {
                            ProductId = 9,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 9,
                            IngredientId = 7
                        },
                        new
                        {
                            ProductId = 9,
                            IngredientId = 8
                        },
                        new
                        {
                            ProductId = 10,
                            IngredientId = 16
                        },
                        new
                        {
                            ProductId = 10,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 10,
                            IngredientId = 22
                        },
                        new
                        {
                            ProductId = 10,
                            IngredientId = 23
                        },
                        new
                        {
                            ProductId = 11,
                            IngredientId = 17
                        },
                        new
                        {
                            ProductId = 11,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 11,
                            IngredientId = 22
                        },
                        new
                        {
                            ProductId = 11,
                            IngredientId = 23
                        },
                        new
                        {
                            ProductId = 12,
                            IngredientId = 16
                        },
                        new
                        {
                            ProductId = 12,
                            IngredientId = 17
                        },
                        new
                        {
                            ProductId = 12,
                            IngredientId = 1
                        },
                        new
                        {
                            ProductId = 12,
                            IngredientId = 21
                        },
                        new
                        {
                            ProductId = 12,
                            IngredientId = 23
                        },
                        new
                        {
                            ProductId = 13,
                            IngredientId = 12
                        },
                        new
                        {
                            ProductId = 13,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 13,
                            IngredientId = 7
                        },
                        new
                        {
                            ProductId = 14,
                            IngredientId = 13
                        },
                        new
                        {
                            ProductId = 14,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 14,
                            IngredientId = 7
                        },
                        new
                        {
                            ProductId = 15,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 15,
                            IngredientId = 11
                        },
                        new
                        {
                            ProductId = 15,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 15,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 16,
                            IngredientId = 19
                        },
                        new
                        {
                            ProductId = 16,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 16,
                            IngredientId = 21
                        },
                        new
                        {
                            ProductId = 17,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 17,
                            IngredientId = 22
                        },
                        new
                        {
                            ProductId = 17,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 18,
                            IngredientId = 21
                        },
                        new
                        {
                            ProductId = 18,
                            IngredientId = 23
                        },
                        new
                        {
                            ProductId = 18,
                            IngredientId = 22
                        },
                        new
                        {
                            ProductId = 19,
                            IngredientId = 19
                        },
                        new
                        {
                            ProductId = 19,
                            IngredientId = 21
                        },
                        new
                        {
                            ProductId = 19,
                            IngredientId = 23
                        },
                        new
                        {
                            ProductId = 19,
                            IngredientId = 22
                        },
                        new
                        {
                            ProductId = 20,
                            IngredientId = 31
                        },
                        new
                        {
                            ProductId = 20,
                            IngredientId = 30
                        },
                        new
                        {
                            ProductId = 21,
                            IngredientId = 32
                        },
                        new
                        {
                            ProductId = 22,
                            IngredientId = 33
                        },
                        new
                        {
                            ProductId = 22,
                            IngredientId = 26
                        },
                        new
                        {
                            ProductId = 22,
                            IngredientId = 29
                        },
                        new
                        {
                            ProductId = 23,
                            IngredientId = 34
                        },
                        new
                        {
                            ProductId = 23,
                            IngredientId = 26
                        },
                        new
                        {
                            ProductId = 24,
                            IngredientId = 35
                        },
                        new
                        {
                            ProductId = 24,
                            IngredientId = 26
                        },
                        new
                        {
                            ProductId = 24,
                            IngredientId = 29
                        },
                        new
                        {
                            ProductId = 25,
                            IngredientId = 24
                        },
                        new
                        {
                            ProductId = 25,
                            IngredientId = 25
                        },
                        new
                        {
                            ProductId = 25,
                            IngredientId = 29
                        },
                        new
                        {
                            ProductId = 25,
                            IngredientId = 27
                        },
                        new
                        {
                            ProductId = 26,
                            IngredientId = 24
                        },
                        new
                        {
                            ProductId = 26,
                            IngredientId = 27
                        },
                        new
                        {
                            ProductId = 26,
                            IngredientId = 29
                        },
                        new
                        {
                            ProductId = 26,
                            IngredientId = 28
                        },
                        new
                        {
                            ProductId = 27,
                            IngredientId = 1
                        },
                        new
                        {
                            ProductId = 27,
                            IngredientId = 26
                        },
                        new
                        {
                            ProductId = 27,
                            IngredientId = 25
                        },
                        new
                        {
                            ProductId = 28,
                            IngredientId = 24
                        },
                        new
                        {
                            ProductId = 28,
                            IngredientId = 26
                        },
                        new
                        {
                            ProductId = 28,
                            IngredientId = 27
                        },
                        new
                        {
                            ProductId = 28,
                            IngredientId = 28
                        });
                });

            modelBuilder.Entity("AklniResturant.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AklniResturant.Models.Order", b =>
                {
                    b.HasOne("AklniResturant.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AklniResturant.Models.OrderItem", b =>
                {
                    b.HasOne("AklniResturant.Models.Order", "Order")
                        .WithMany("OrdersItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AklniResturant.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AklniResturant.Models.Product", b =>
                {
                    b.HasOne("AklniResturant.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AklniResturant.Models.ProductIngredient", b =>
                {
                    b.HasOne("AklniResturant.Models.Ingredient", "Ingredient")
                        .WithMany("ProdIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AklniResturant.Models.Product", "Product")
                        .WithMany("ProdIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AklniResturant.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AklniResturant.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AklniResturant.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AklniResturant.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AklniResturant.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AklniResturant.Models.Ingredient", b =>
                {
                    b.Navigation("ProdIngredients");
                });

            modelBuilder.Entity("AklniResturant.Models.Order", b =>
                {
                    b.Navigation("OrdersItems");
                });

            modelBuilder.Entity("AklniResturant.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProdIngredients");
                });

            modelBuilder.Entity("AklniResturant.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
